parameters:
  rc_amcharts.twig_extension.class: RC\AmChartsBundle\Twig\AmChartsExtension

services:
  rc_amcharts.twig.amcharts_extension:
    class: '%rc_amcharts.twig_extension.class%'
    tags:
        - { name: twig.extension }
